name: Ghost
version: 1.0
api: 4.0.0
main: MuhammedHk18\Ghost\Main
author: MuhammedHk18

commands:
  ghost:
    permission: ghost.permission
    description: enter ghost mode
  ghostlist:
    description: see all ghost players
    permission: ghost.listcommand

permissions:
  ghost.permission:
    description: ghost mode all permission
    default: true
  ghost.listcommand:
    description: ghost list permission
    default: op